receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

  transform:
    log_statements:
      - context: log
        statements:
          - replace_pattern(severity_text, "SEVERITY_NUMBER_", "")

exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000
    database: default
    create_schema: true
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [transform, batch]
      exporters: [clickhouse]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
